goal:
  waypoints:
  - [ -2.0,  -2.0, 0.0 ] #test wp 1
  - [ -1.0,  -2.0, 1.5707 ] #test wp 2
#  - [ 1.0372010231 ,  -2.11601295471, 0.0 ]
#  - [2.5786190033 ,  -1.27291088104, 4.7123]
#  - [1.22448043823 ,  1.54275131226, 0.0]
#  - [1.60902767182 ,  -1.22517471314, 4.7123]
#  - [-0.0717240810394 ,  -1.51570167542, 1.5707]
#  - [1.01269788742 ,  1.22541341782, 0.0]
#  - [-0.638660955429 ,  1.26275787354, 4.7123]
#  - [-2.2607093811 ,  0.97490968704, 3.1415]
#  - [-2.32547740936 ,  -1.32274684906, 4.7123]

  reached_waypoint_stop_time: 3

  # East  = 0*pi/2 = 0.0000
  # North = 1*pi/2 = 1.5707
  # West  = 2*pi/2 = 3.1415
  # South = 3*pi/2 = 4.7123
