wps:
  - [-3.10801386833, 4.88111925125, -1.52614450226]
  - [-2.12524914742, -1.60717535019, 1.55841375286]
  - [2.32184529305, -3.40717220306, 2.37683575141]
  - [1.73485660553, 3.14053320885, -0.0238841612192]
  - [ 0.498698890209, -0.629815876484, 0.0370545326235]

